# Site settings
title: Andrew C. Meier
email: ameier@easury.com
description: >-
  Notebook of Andrew C. Meier. Originally
  from STL, now living in NYC. Working in FinTech. Passionate about
  consumer finance, capital markets, functional programming, and DevOps.
baseurl: "/"
url: "https://andrewcmeier.com"
twitter_username: ameier38
github_username:  ameier38

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jemoji
  - jekyll-feed

exclude:
  - LICENSE
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
