# Site settings
title: Andrew C. Meier
description: Made in the USA <img src='/assets/images/america.svg' />
baseurl: "/"
url: "https://andrewcmeier.com"
twitter_username: ameier38
github_username:  ameier38

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jemoji
  - jekyll-feed

exclude:
  - LICENSE
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
